version: '3.8'

services:
  app:
    build: .
    command: ["./wait-for-db.sh", "db", "5432", "npm", "start"]
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork

  db:
    image: postgres
    environment:
      POSTGRES_DB: "text"
      POSTGRES_USER: "EDINSON"
      POSTGRES_PASSWORD: "ED"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U EDINSON -d text"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

networks:
  mynetwork:
